services:
  backend:
    build: ./backend
    container_name: ocr-backend
    ports:
      - "8080:8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/gcp-key.json
    volumes:
      - ./backend/service_account.json:/var/secrets/gcp-key.json:ro
    env_file:
      - ./backend/.env
    networks:
      - ocr-network

  frontend:
    build: ./frontend
    container_name: ocr-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge
